version: '3.8'

services:
  backend:
    build:
      context: .
      target: backend
    container_name: agentdock-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    networks:
      - agentdock-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: .
      target: frontend
    container_name: agentdock-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - agentdock-network
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api

networks:
  agentdock-network:
    driver: bridge